CREATE DATABASE TRG
USE TRG

CREATE TABLE ITEMS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ITEMCODE VARCHAR(10),
	ITEMNAME VARCHAR(50)
)

INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME]) 
VALUES ('URUN001', 'URUN 1')
INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME]) 
VALUES ('URUN002', 'URUN 2')
INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME]) 
VALUES ('URUN003', 'URUN 3')
INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME]) 
VALUES ('URUN004', 'URUN 4')
SELECT * FROM ITEMS

TRUNCATE TABLE ITEMS
DECLARE @I INT = 1
WHILE @I < 10
BEGIN
	INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME])  VALUES
	('URUN00' + CAST(@I AS VARCHAR(1)), 'URUN '+ CAST(@I AS VARCHAR(1)))
	SET @I = @I + 1
END
SELECT * FROM ITEMS
---------
DECLARE @I INT = 10
WHILE @I < 100
BEGIN
	INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME])  VALUES
	('URUN0' + CAST(@I AS VARCHAR(2)), 'URUN '+ CAST(@I AS VARCHAR(2)))
	SET @I = @I + 1
END
SELECT * FROM ITEMS
---------
DECLARE @I INT = 100
WHILE @I < 1000
BEGIN
	INSERT INTO ITEMS ( [ITEMCODE], [ITEMNAME])  VALUES
	('URUN' + CAST(@I AS VARCHAR(3)), 'URUN '+ CAST(@I AS VARCHAR(3)))
	SET @I = @I + 1
END
SELECT * FROM ITEMS
------------------------
CREATE TABLE ITEMTRANSACTIONS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ITEMID INT ,
	DATE_ DATETIME,
	AMOUNT INT,
	IOTYPE SMALLINT 
)

---------------------------
---------------------------
TRUNCATE TABLE ITEMTRANSACTIONS
---------------------------
DECLARE @ITEMID AS INT
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTYPE AS SMALLINT
DECLARE @J INT
SET @J = 0
WHILE @J < 100000
BEGIN
	SET @ITEMID = ROUND(RAND() * 999 , 0) + 1
	SET @DATE = DATEADD(DAY, -ROUND(RAND() * 365 ,0 ), GETDATE())  
	SET @AMOUNT = ROUND(RAND() * 9 , 0) + 1
	SET @IOTYPE = ROUND(RAND() * 1 , 0) + 1
	INSERT INTO ITEMTRANSACTIONS (ITEMID, DATE_, AMOUNT, IOTYPE)
	VALUES (@ITEMID, @DATE, @AMOUNT, @IOTYPE)
	SET @J = @J +1
END
SELECT * FROM ITEMTRANSACTIONS
