SELECT * FROM ITEMS 
-----
----
---
SELECT * FROM ITEMTRANSACTIONS WHERE ITEMID = 1
-----
----
---
SELECT IOTYPE, SUM(AMOUNT), COUNT(IOTYPE) FROM ITEMTRANSACTIONS WHERE ITEMID = 1
GROUP BY IOTYPE
-----
----
---
SET STATISTICS IO ON
SELECT *,  
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE = 1 ) 
- (SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE = 2 ) AS STOK
FROM ITEMS  ITM

--------------------------------
--------------------------------
--------------------------------
CREATE TABLE STOCK
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ITEMID INT,
	STOCK INT,
)


SET STATISTICS IO ON
SELECT ID,  
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE = 1 ) 
- (SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE = 2 ) AS STOK
FROM ITEMS  ITM
ORDER BY ID

SET STATISTICS IO ON
SELECT * FROM STOCK

