CREATE TRIGGER TRG_TRANSACTION_UPDATE
ON ITEMTRANSACTIONS 
AFTER UPDATE 
AS 
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @IOTYPE AS SMALLINT
	DECLARE @OLDAMOUNT AS INT
	DECLARE @NEWAMOUNT AS INT
	DECLARE @AMOUNT AS INT
	SELECT @ITEMID = ITEMID, @OLDAMOUNT = AMOUNT, @IOTYPE = IOTYPE FROM DELETED
	SELECT @NEWAMOUNT = AMOUNT FROM INSERTED
	SELECT @AMOUNT = @OLDAMOUNT - @NEWAMOUNT

	IF @IOTYPE = 1
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID 
	IF @IOTYPE = 2
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID 

END

SELECT * FROM ITEMS WHERE ID = 1
SELECT * FROM ITEMTRANSACTIONS WHERE ITEMID = 1
SELECT * FROM ITEMTRANSACTIONS WHERE ITEMID = 3
SELECT * FROM STOCK WHERE ITEMID = 1

UPDATE ITEMTRANSACTIONS SET AMOUNT = 10 WHERE ID = 3
DELETE FROM ITEMTRANSACTIONS WHERE ID = 1