CREATE TRIGGER TRG_TRANSACTION_INSERT
ON WORKERTRANSACTIONS
AFTER INSERT
AS

BEGIN
	DECLARE @WORKERID AS INT 
	DECLARE @DATE AS DATETIME
	DECLARE @IOTYPE AS VARCHAR(1)
	SELECT @WORKERID = WORKERID, @DATE = DATE_,@IOTYPE = IOTYPE FROM INSERTED
	UPDATE WORKER_LAST_TRANSACTIONS SET LASTIOTYPE = @IOTYPE, LASTDATE = @DATE 
	WHERE WORKERID = @WORKERID
END

SELECT * FROM [dbo].[WORKER_LAST_TRANSACTIONS]
TRUNCATE TABLE [dbo].[WORKERTRANSACTIONS]
SELECT * FROM [dbo].[WORKERTRANSACTIONS]

--------------------------------------------
EXEC GENERATE_WORKER_TRANSACTION 1
SELECT * FROM [dbo].[WORKER_LAST_TRANSACTIONS]

--------------------------------------------------
TRUNCATE TABLE [dbo].[WORKERTRANSACTIONS]
DECLARE @I AS INT = 1
WHILE @I <= 1000
BEGIN
	EXEC GENERATE_WORKER_TRANSACTION @I
	SET @I = @I + 1
END
SELECT * FROM [dbo].[WORKER_LAST_TRANSACTIONS]
