use ETRADE
create TABLE ITEMS_LOG
(
	ID INT ,
	ITEMCODE VARCHAR(50),
	ITEMNAME VARCHAR(50),
	UNITRICE VARCHAR(50),
	CATEGORY1 VARCHAR(50),
	CATEGORY2 VARCHAR(50),
	CATEGORY3 VARCHAR(50),
	CATEGORY4 VARCHAR(50),
	BRAND VARCHAR(50),
	LOG_ACTIONTYPE VARCHAR(20),
	LOG_DATE DATETIME,
	LOG_USERNAME VARCHAR(50),
	LOG_PROGRAMNAME VARCHAR(50),
	LOG_HOSTNAME VARCHAR(50)
 )

 -----------------------
 SELECT * FROM ITEMS_LOG
 -----------------------
 CREATE TRIGGER TRG_ITEMS_UPDATE
 ON ITEMS
 AFTER UPDATE
 AS
BEGIN
	INSERT INTO ITEMS_LOG ([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], 
	[LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 'UPDATE',GETDATE(),SUSER_NAME(),
	PROGRAM_NAME(), HOST_NAME()
	FROM DELETED

END

UPDATE ITEMS SET UNITPRICE  = 25 WHERE ID = 6
SELECT * FROM ITEMS_LOG
UPDATE ITEMS SET UNITPRICE  = 35 WHERE ID = 6
SELECT * FROM ITEMS_LOG
----------------------------------------------------------
 CREATE TRIGGER TRG_ITEMS_DELETE
 ON ITEMS
 AFTER DELETE
 AS
BEGIN
	INSERT INTO ITEMS_LOG ([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], 
	[LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 'DELETE',GETDATE(),SUSER_NAME(),
	PROGRAM_NAME(), HOST_NAME()
	FROM DELETED

END


DELETE FROM ITEMS   WHERE ID = 6
SELECT * FROM ITEMS_LOG 


--------------------------------------
DROP TRIGGER TRG_ITEMS_DELETE
DROP TRIGGER TRG_ITEMS_UPDATE
---------------------------------------

CREATE TRIGGER TRG_ITEMS_DELETE_UPDATE
ON ITEMS
AFTER DELETE, UPDATE
AS
BEGIN
	DECLARE @DELETEDCOUNT AS INT
	DECLARE @INSERTEDCOUNT AS INT
	DECLARE @UPDATETEDCOUNT AS INT
	SELECT @DELETEDCOUNT = COUNT( *) FROM DELETED
	SELECT @INSERTEDCOUNT = COUNT( *) FROM inserted
	DECLARE @LOG_ACTIONTYPE AS VARCHAR(20)
	IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT>0
		SET @LOG_ACTIONTYPE = 'UPDATE'
	IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT = 0
		SET @LOG_ACTIONTYPE = 'DELETE'
	INSERT INTO ITEMS_LOG ([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], 
	[LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], @LOG_ACTIONTYPE,GETDATE(),SUSER_NAME(),
	PROGRAM_NAME(), HOST_NAME()
	FROM DELETED
END

UPDATE ITEMS SET UNITPRICE  = 25 WHERE ID = 7
SELECT * FROM ITEMS_LOG
UPDATE ITEMS SET UNITPRICE  = 35 WHERE ID = 7
SELECT * FROM ITEMS_LOG
DELETE FROM ITEMS   WHERE ID = 7
SELECT * FROM ITEMS_LOG 
