USE ETRADE 
DELETE FROM  ITEMS WHERE ID = 3
SELECT * FROM ITEMS_LOG WHERE ID = 3

-------------------------------
CREATE TRIGGER TRG_ITEMS_DELETE_UPDATE_INSTEADOF
ON ITEMS
INSTEAD OF DELETE, UPDATE
AS
BEGIN
	DECLARE @DELETEDCOUNT AS INT
	DECLARE @INSERTEDCOUNT AS INT
	DECLARE @UPDATETEDCOUNT AS INT
	SELECT @DELETEDCOUNT = COUNT( *) FROM DELETED
	SELECT @INSERTEDCOUNT = COUNT( *) FROM inserted
	DECLARE @LOG_ACTIONTYPE AS VARCHAR(20)
	IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT>0
		SET @LOG_ACTIONTYPE = 'UPDATE'
	IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT = 0
		SET @LOG_ACTIONTYPE = 'DELETE'
	INSERT INTO ITEMS_LOG ([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], 
	[LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1],
	[CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], @LOG_ACTIONTYPE,GETDATE(),SUSER_NAME(),
	PROGRAM_NAME(), HOST_NAME()
	FROM DELETED
END

---- DISABLE TRIGGER TRG_ITEMS_DELETE_UPDATE
DELETE FROM  ITEMS WHERE ID = 5
SELECT * FROM ITEMS_LOG WHERE ID = 5
SELECT * FROM ITEMS WHERE ID = 5
