create databasE BANKA
USE BANKA

------------------
CREATE TABLE CUSTOMERS
(
	ID INT IDENTITY PRIMARY KEY,
	CUSTOMERNAME VARCHAR (50)

)
CREATE TABLE ACCOUNTS
(
	ID INT IDENTITY PRIMARY KEY,
	CUSTOMERID INT ,
	ACCOUNTNO VARCHAR (50),
	ACCOUNTNAME VARCHAR(50),
	CURENCY VARCHAR(3),
)
CREATE TABLE ACCOUNTBALANCE
(
	ID INT IDENTITY PRIMARY KEY,
	ACCOUNTID INT,
	BALANCE FLOAT,
	CURENCY VARCHAR(3),
)
CREATE TABLE MONEYTRANSACTIONS
(
	ID INT IDENTITY PRIMARY KEY,
	ACCOUNTID VARCHAR (50),
	TRANTYPE INT,
	AMOUNT FLOAT,
	DATE_ DATETIME,
	EFTCODE1 VARCHAR(10),
	EFTCODE2 VARCHAR(10),

)
-------------------------------------
INSERT INTO CUSTOMERS (CUSTOMERNAME) VALUES ('AHMET')
INSERT INTO CUSTOMERS (CUSTOMERNAME) VALUES ('ÖMER')
INSERT INTO ACCOUNTS (CUSTOMERID, ACCOUNTNO, ACCOUNTNAME, CURENCY) VALUES (1, 'HESAPNO1','AHMETÝN HESABI', 'TL')
INSERT INTO ACCOUNTS (CUSTOMERID, ACCOUNTNO, ACCOUNTNAME, CURENCY) VALUES (2, 'HESAPNO2','ÖMERÝN HESABI', 'TL')
INSERT INTO ACCOUNTBALANCE (ACCOUNTID, BALANCE, CURENCY) VALUES (1,1000,'TL') 
INSERT INTO ACCOUNTBALANCE (ACCOUNTID, BALANCE, CURENCY) VALUES (2,0,'TL') 
----------------------------------------


SELECT * FROM CUSTOMERS
SELECT * FROM ACCOUNTS
SELECT * FROM ACCOUNTBALANCE

SELECT * FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

SELECT C.CUSTOMERNAME, A.ACCOUNTNO, A.ACCOUNTNAME, A.CURENCY, B.BALANCE FROM ACCOUNTBALANCE B
INNER JOIN ACCOUNTS A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID


