-- Ürün Analizi
select 
itm.ITEMCODE MALZEMEKODU, itm.ITEMNAME MALZEMEADI, MIN(OD.UNITPRICE) AS ENDUSUKFIYAT, 
MAX(OD.UNITPRICE) ENYUKSEKFIYAT, AVG(OD.UNITPRICE) AS ORTALAMAFIYAT,
SUM(OD.LINETOTAL) TOPLAMSATISTUTAR, SUM(OD.AMOUNT) AS TOPLAMSATISMIKTAR
from 
ORDERDETAILS od
inner join ORDERS o on od.ORDERID = o.ID
inner join ITEMS itm on itm.ID = od.ITEMID
GROUP BY itm.ITEMCODE, itm.ITEMNAME

-------------------------------------
select 
ITM.ITEMCODE MALZEMEKODU, ITM.ITEMNAME MALZEMEADI,
	(SELECT MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENDUSUKFIYAT,
	(SELECT MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ENYUKSEKFIYAT,
	(SELECT AVG(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = ITM.ID) AS ORTALAMAFIYAT
from ITEMS ITM 
-------------------------------------------

CREATE FUNCTION DBO.GET_ITEM_MINPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE  @RESULT AS FLOAT
	SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_MAXPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE  @RESULT AS FLOAT
	SELECT @RESULT = MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_AVGPRICE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE  @RESULT AS FLOAT
	SELECT @RESULT = AVG(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	RETURN @RESULT
END
CREATE FUNCTION DBO.GET_ITEM_TOTALSALE(@ITEMID AS INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE  @RESULT AS FLOAT
	SELECT @RESULT = SUM(LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	RETURN @RESULT
END

select TOP 100
ITM.ID, ITM.ITEMCODE MALZEMEKODU, ITM.ITEMNAME MALZEMEADI,
DBO.GET_ITEM_MINPRICE(ITM.ID) AS ENDUSUKFÝYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS ENYUKSEKKFÝYAT
from ITEMS ITM 
----6 SANIYE
-----------------------------
USE [ETRADE]

GO

CREATE NONCLUSTERED INDEX [IX1] ON [dbo].[ORDERDETAILS]
(
	[ITEMID] ASC
)
INCLUDE([AMOUNT],[UNITPRICE],[LINETOTAL]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO
----------------------------
UPDATE STATISTICS ORDERDETAILS
select 
ITM.ID, ITM.ITEMCODE MALZEMEKODU, ITM.ITEMNAME MALZEMEADI,
DBO.GET_ITEM_MINPRICE(ITM.ID) AS ENDUSUKFÝYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS ENYUKSEKKFÝYAT,
DBO.GET_ITEM_AVGPRICE(ITM.ID) AS ORTALAMAKFÝYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS TOPLAMSATIS
from ITEMS ITM 
--- 28000 - 3 SANIYE