CREATE FUNCTION DBO.GET_ITEM_PRICE(@ITEMID AS INT, @PRICETYPE AS VARCHAR(10))
RETURNS FLOAT
AS
BEGIN
	DECLARE  @RESULT AS FLOAT
	IF @PRICETYPE = 'MIN'
	BEGIN
		SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	END
	IF @PRICETYPE = 'MAX'
	BEGIN
		SELECT @RESULT = MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	END
	IF @PRICETYPE = 'AVG'
	BEGIN
		SELECT @RESULT = AVG(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID 
	END
	RETURN @RESULT
END

-------------------------------------------------

select 
ITM.ID, ITM.ITEMCODE MALZEMEKODU, ITM.ITEMNAME MALZEMEADI,
DBO.GET_ITEM_PRICE(ITM.ID, 'MIN') AS ENDUSUKFÝYAT,
DBO.GET_ITEM_PRICE(ITM.ID, 'MAX') AS ENYUKSEKKFÝYAT,
DBO.GET_ITEM_PRICE(ITM.ID, 'AVG') AS ORTALAMAKFÝYAT
from ITEMS ITM 